kind: pipeline
type: docker
name: mypy

platform:
  os: linux
  arch: arm64

steps:
- name: mypy-base
  image: python:3.10.1
  commands:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - python3 -m mypy .

trigger:
  branch:
    - master
  event:
    - pull_request

node:
  type: test
